security:
    encoders:
        Runroom\AdminUserBundle\Entity\User: auto
    access_control:
        - { path: ^/backoffice/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/backoffice/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/backoffice/reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/, role: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_RUNROOM_ADMIN_USER_ADMIN_USER_VIEW
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
    access_decision_manager:
        strategy: unanimous
    providers:
        app_user_provider:
            entity:
                class: Runroom\AdminUserBundle\Entity\User
                property: email
    firewalls:
        backoffice:
            anonymous: lazy
            pattern: /backoffice(.*)
            switch_user: true
            user_checker: Runroom\AdminUserBundle\Security\UserChecker
            guard:
                authenticators:
                    - Runroom\AdminUserBundle\Security\AdminAuthenticator
            logout:
                path: admin_logout
                target: admin_login
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 2629746
                path: /backoffice
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
