sonata_admin:
    title: Backoffice
    title_logo: build/img/logo_backoffice.png
    show_mosaic_button: false
    security:
        handler: sonata.admin.security.handler.role
        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
    templates:
        layout: sonata/standard_layout.html.twig
        user_block: security/user_block.html.twig
    dashboard:
        groups:
            runroom:
                label: Base
                items:
                    - runroom.base.admin.meta_information
                    - runroom.admin_user.admin.user
                    - runroom.static_page.admin.static_page
                    - runroom.translation.admin.translation
                    - runroom.redirection.admin.redirect
                    - label: Cookies
                      route: admin_runroom_cookies_cookiespage_edit
                      route_params: { id: 1 }
            demo:
                label: Demo
                items:
                    - archetype.demo.admin.book
                    - archetype.demo.admin.category
                    - archetype.demo.admin.contact
            media:
                label: Media
                icon: <i class="fa fa-photo"></i>
                on_top: true
                items:
                    - sonata.media.admin.media
