parameters:
    locale: en
    x_default_locale: en
    locales: [en, es, ca]
    assets_version: 1.0.0
    container.dumper.inline_class_loader: true
    doctrine_behaviors_translatable_fetch_mode: EAGER
    doctrine_behaviors_translation_fetch_mode: EAGER

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locales: '%locales%'

    App\:
        resource: ../src/App/*

    App\Controller\:
        resource: ../src/App/Controller
        public: true
        tags: [controller.service_arguments]

    App\Service\MailService:
        bind:
            $from: '%env(MAILER_FROM)%'
            $bcc: '%env(json:MAILER_BCC)%'

    Jaybizzle\CrawlerDetect\CrawlerDetect: null

    Gedmo\Sluggable\SluggableListener:
        calls:
            - [setAnnotationReader, ['@annotation_reader']]
        tags:
            - { name: doctrine.event_subscriber }

    Gedmo\Sortable\SortableListener:
        calls:
            - [setAnnotationReader, ['@annotation_reader']]
        tags:
            - { name: doctrine.event_subscriber }

    app.admin.gallery:
        class: App\Admin\GalleryAdmin
        public: true
        arguments: [~, App\Entity\Gallery, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Gallery' }

    app.admin.gallery_image:
        class: App\Admin\GalleryImageAdmin
        public: true
        arguments: [~, App\Entity\GalleryImage, Runroom\SortableBehaviorBundle\Controller\SortableAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'GalleryImage' }

    app.admin.user:
        class: App\Admin\UserAdmin
        public: true
        arguments: [~, App\Entity\User, ~]
        calls:
            - [setUserManager, ['@fos_user.user_manager']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'User' }

    app.admin.module:
        class: App\Admin\Module\ModuleAdmin
        public: true
        arguments: [~, App\Entity\Module\Module, Runroom\SortableBehaviorBundle\Controller\SortableAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Module' }

    app.admin.page:
        class: App\Admin\PageAdmin
        public: true
        arguments: [~, App\Entity\Page, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Page' }
        calls:
            - [addChild, ['@app.admin.module', 'page']]

    app.admin.extension.wysiwyg_module:
        class: App\Admin\Module\WysiwygModuleAdminExtension
        tags:
            - { name: sonata.admin.extension, target: app.admin.module }

    app.admin.menu_item:
        class: App\Admin\MenuItemAdmin
        arguments: [~, App\Entity\MenuItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: MenuItem }
        public: true
